#!/usr/bin/env python3
"""Build the distributable mcpsim data bundle from the (read-only) source repo.

The bundle preserves the source-repo directory layout, so consumers simply
point MCPSIM_SOURCE_REPO at the unpacked bundle. A sha256 manifest
(data/MANIFEST.yaml in this repo; MANIFEST.yaml inside the bundle) records
every file; `mcpsim install --check-data` verifies a machine's copy.

Usage (author-side):
    python tools/make_data_bundle.py --manifest-only         # refresh data/MANIFEST.yaml
    python tools/make_data_bundle.py --out /tmp/bundle       # fast+legacy-cpp sets
    python tools/make_data_bundle.py --out /tmp/bundle --sets fast,legacy-cpp,samples

Sets:
    fast        everything fast mode needs for all presets (~355 MB raw)
    legacy-cpp  the C++ sources for the cpp engine / regeneration (~120 KB)
    samples     archived 120 GeV PYTHIA parent samples (~3 GB, python engine)
"""

from __future__ import annotations

import argparse
import hashlib
import shutil
import sys
import tarfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from mcpsim import paths  # noqa: E402

# Patterns are relative to the source repo; every match is bundled.
SETS = {
    "fast": [
        "data-backup/mship_values.txt",
        "data-backup/mship_values_copy.txt",
        "data-backup/total_efficiency_outputdecayPionDARK.txt",
        "data-backup/total_efficiency_outputdecayEtaDARK.txt",
        "data-backup/total_efficiency_output2bodydecay-rho.txt",
        "data-backup/total_efficiency_output2bodydecay-omega.txt",
        "data-backup/total_efficiency_output2bodydecay-phi.txt",
        "data-backup/total_efficiency_output2body_decay-jsi.txt",
        "data-backup/total_efficiency_outputdecayPion_SHIP-1m-small.txt",
        "data-backup/total_efficiency_outputdecayEta_SHIP-1m-small.txt",
        "data-backup/total_efficiency_output2bodydecay-rho-SHIP.txt",
        "data-backup/total_efficiency_output2bodydecay-omega-SHIP.txt",
        "data-backup/total_efficiency_output2bodydecay-phi-SHIP.txt",
        "data-backup/total_efficiency_output2body_decay-jsi-SHiP.txt",
        "data-backup/dy_cross_darkquest_nCTEQ15_iron.txt",
        "data-backup/ageo_darkquest_nCTEQ15_iron.txt",
        "data-backup/dy_cross_ship_nCTEQ15_iron.txt",
        "data-backup/ageo_ship_nCTEQ_iron.txt",
        "data-backup/LXPLUS_BREM.md",
        "data-backup/mCP_brem.py",
        "DarkQuest-brem-backup/Brem_120GeV_*.txt",
        "SHiP-brem-backup/Brem_400GeV_*.txt",
        "experiment-contours-small/MiniBooNE.csv",
        "experiment-contours-small/SLACmQ.csv",
        "experiment-contours-small/BEBC.csv",
        "experiment-contours-small/LSND.csv",
        "experiment-contours-small/CHARMII.csv",
        "experiment-contours-small/ArgoNeuT.csv",
        "experiment-contours-small/SENSEI_POLISHED.csv",
        "experiment-contours-small/milliQanRun3Fix.csv",
        "lanl_12bar_pipeline/README.md",
        "lanl_12bar_pipeline/output/lanl_12bar_pi0_ER1_legacy_5M_mship_cebr3x2x2_efficiencies.txt",
        "lanl_12bar_pipeline/output/lanl_12bar_eta_ER1_legacy_5M_mship_cebr3x2x2_efficiencies.txt",
    ],
    "legacy-cpp": [
        "mesongen-backup/mesonGen.cc",
        "mesongen-backup/momentum.config",
        "mesongen-backup/beam.config",
        "mesongen-backup/CMakeLists.txt",
        "lanl_12bar_pipeline/generatePion_12bar.cc",
        "lanl_12bar_pipeline/lanl_decayPion_12bar.cc",
        "decay-backup/decayVectorMeson.cc",
        "decay-backup/decayPion.cc",
    ],
    "samples": [
        "mesongen-backup/output-data/debugPi0.root",
        "mesongen-backup/output-data/debugEta.root",
        "mesongen-backup/output-data/debugRHO.root",
        "mesongen-backup/output-data/debugOmega.root",
        "mesongen-backup/output-data/debugPhi.root",
        "mesongen-backup/output-data/debugJsi.root",
    ],
}

MANIFEST_PATH = Path(__file__).resolve().parents[1] / "data" / "MANIFEST.yaml"


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def collect(repo: Path, sets):
    """Yield (set_name, relative_path) for every matched file."""
    for set_name in sets:
        for pattern in SETS[set_name]:
            matches = sorted(repo.glob(pattern))
            if not matches:
                print(f"WARNING: no match for {pattern!r} in {repo}", file=sys.stderr)
            for m in matches:
                if m.is_file():
                    yield set_name, m.relative_to(repo)


def write_manifest(repo: Path, entries, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by tools/make_data_bundle.py — do not edit by hand.",
             f"# Source tree: {repo}", "files:"]
    total = 0
    for set_name, rel in entries:
        p = repo / rel
        size = p.stat().st_size
        total += size
        lines.append(f"  - path: {rel}")
        lines.append(f"    set: {set_name}")
        lines.append(f"    size: {size}")
        lines.append(f"    sha256: {sha256(p)}")
    lines.append(f"total_bytes: {total}")
    dest.write_text("\n".join(lines) + "\n")
    print(f"manifest: {dest}  ({len([e for e in entries])} files, "
          f"{total/1e6:.1f} MB)")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path, default=None,
                    help="bundle output directory (omit with --manifest-only)")
    ap.add_argument("--sets", default="fast,legacy-cpp",
                    help=f"comma list of {', '.join(SETS)} [default: fast,legacy-cpp]")
    ap.add_argument("--manifest-only", action="store_true",
                    help="only refresh data/MANIFEST.yaml (all sets)")
    ap.add_argument("--no-tar", action="store_true", help="skip the tar.gz step")
    args = ap.parse_args()

    repo = paths.require_source_repo()
    if args.manifest_only:
        entries = list(collect(repo, list(SETS)))
        write_manifest(repo, entries, MANIFEST_PATH)
        return 0

    if args.out is None:
        ap.error("--out is required unless --manifest-only")
    sets = [s.strip() for s in args.sets.split(",")]
    unknown = set(sets) - set(SETS)
    if unknown:
        ap.error(f"unknown set(s) {sorted(unknown)}; valid: {', '.join(SETS)}")

    bundle = args.out / "mcpsim-data"
    entries = list(collect(repo, sets))
    for _, rel in entries:
        dst = bundle / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(repo / rel, dst)
    write_manifest(repo, entries, bundle / "MANIFEST.yaml")

    if not args.no_tar:
        tag = "-".join(sets)
        tar_path = args.out / f"mcpsim-data-{tag}.tar.gz"
        with tarfile.open(tar_path, "w:gz") as tf:
            tf.add(bundle, arcname="mcpsim-data")
        print(f"bundle: {tar_path}  ({tar_path.stat().st_size/1e6:.1f} MB)")
    print(f"unpacked bundle: {bundle}\n"
          f"use with: export MCPSIM_SOURCE_REPO={bundle}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
